site_name: "No Clocks DNS Documentation"
site_description: "Domain Name Server (DNS) Records Infrastructure as Code (IaC) for No Clocks, LLC's domain hosted at [noclocks.dev](https://noclocks.dev)"
site_author: "No Clocks, LLC"
site_url: "https://docs.noclocks.dev/dns"

docs_dir: docs
site_dir: site

repo_url: https://github.com/noclocks/dns
repo_name: noclocks/dns
edit_uri: edit/main/docs

copyright: Copyright &copy; 2024 No Clocks, LLC

plugins:
  - search
  - material-plausible
  # - git-revision-date-localized:
  #     enable_creation_date: true
  # - git-committers:
  #     repository: noclocks/cdn
  #     branch: main
  # - git-authors

theme:
  name: material
  logo: assets/img/logo.png
  favicon: assets/img/logo.png
  icon:
    repo: fontawesome/brands/git-alt
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  palette:
    # Palette toggle for dark mode
    - scheme: slate
      primary: black
      accent: cyan
      toggle:
        icon: material/weather-sunny
        name: Switch to Light Mode
    # Palette toggle for light mode
    - scheme: default
      primary: white
      accent: cyan
      toggle:
        icon: material/weather-night
        name: Switch to Dark Mode
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.tracking
    - navigation.path
    - navigation.prune
    - navigation.indexes
    - navigation.sections
    - navigation.footer
    - toc.follow
    - toc.integrate
    - search.suggest
    - search.highlight
    - search.share
    - content.action.edit

extra:
  analytics:
    provider: plausible
    domain: docs.noclocks.dev
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: good
          note: >-
            Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: bad
          note: >-
            Thanks for your feedback! Help us improve this page by
            using our <a href="..." target="_blank" rel="noopener">feedback form</a>.
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/noclocks
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/noclocksdev
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/company/noclocks
    - icon: fontawesome/brands/youtube
      link: https://youtube.com/noclocks
    - icon: fontawesome/brands/facebook
      link: https://facebook.com/noclocksdev
    - icon: fontawesome/brands/slack
      link: https://noclocks.slack.com
    - icon: fontawesome/brands/instagram
      link: https://instagram.com/noclocksdev
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/u/noclocks

