name: DNSControl

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  PORKBUN_API_KEY: ${{ secrets.PORKBUN_API_KEY }}
  PORKBUN_API_SECRET: ${{ secrets.PORKBUN_API_SECRET }}
  SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

jobs:
  dnscontrol:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check
        uses: koenrh/dnscontrol-action@v3
        with:
          args: check
          config_file: 'dnsconfig.js'
          creds_file: 'creds.example.json'

      - name: Push
        uses: koenrh/dnscontrol-action@v3
        with:
          args: push
          config_file: 'dnsconfig.js'
          creds_file: 'creds.example.json'
