name: Preview DNS Changes

on:
  pull_request:
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  PORKBUN_API_KEY: ${{ secrets.PORKBUN_API_KEY }}
  PORKBUN_API_SECRET: ${{ secrets.PORKBUN_API_SECRET }}

jobs:
  dnscontrol:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check
        uses: koenrh/dnscontrol-action@v3
        with:
          args: check
          config_file: 'dnscontrol.js'
          creds_file: 'creds.example.json'

      - name: Preview
        id: dnscontrol_preview
        uses: koenrh/dnscontrol-action@v3
        with:
          args: preview
          config_file: 'dnscontrol.js'
          creds_file: 'creds.example.json'

      - name: Comment
        uses: mshick/add-pr-comment@v2
        with:
          message: |
            ```
            ${{ steps.dnscontrol_preview.outputs.preview_comment }}
            ```
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          allow-repeats: true
